_libtorch_env = {"DYLD_LIBRARY_PATH": "third_party/libtorch/lib"}

cxx_test(
    name = "test_abstract_state",
    srcs = ["test_abstract_state.cpp"],
    deps = ["//neural_cfr:core", "//third_party:gtest"],
    compiler_flags = ["-std=c++17"],
    env = _libtorch_env,
)

cxx_test(
    name = "test_features",
    srcs = ["test_features.cpp"],
    deps = ["//neural_cfr:core", "//third_party:gtest", "//third_party:libtorch"],
    compiler_flags = ["-std=c++17"],
    env = _libtorch_env,
)

cxx_test(
    name = "test_reservoir_buffer",
    srcs = ["test_reservoir_buffer.cpp"],
    deps = ["//neural_cfr:core", "//third_party:gtest"],
    compiler_flags = ["-std=c++17"],
    env = _libtorch_env,
)

cxx_test(
    name = "test_traversal",
    srcs = ["test_traversal.cpp"],
    deps = ["//neural_cfr:core", "//third_party:gtest", "//third_party:libtorch"],
    compiler_flags = ["-std=c++17"],
    env = _libtorch_env,
)
