_python_include = read_config("python", "include_path", "")

cxx_library(
    name = "sixmax",
    srcs = ["src/bindings/bindings.cpp"],
    header_namespace = "",
    compiler_flags = ["-std=c++17", "-O2"] +
                     (["-I" + _python_include] if _python_include else []),
    deps = ["//common:evaluator", "//third_party:pybind11"],
    preferred_linkage = "shared",
    soname = "sixmax.so",
    linker_flags = ["-undefined", "dynamic_lookup"],
    visibility = ["PUBLIC"],
)
