cxx_library(
    name = "evaluator",
    srcs = ["src/game/card.cpp", "src/game/safe_eval.cpp"],
    headers = ["src/game/card.h", "src/game/safe_eval.h"],
    header_namespace = "",
    compiler_flags = ["-std=c++17", "-O2"],
    exported_preprocessor_flags = ["-Icommon/src", "-Icommon/src/game"],
    preferred_linkage = "static",
    visibility = ["PUBLIC"],
)
